name: React Native build android

on: workflow_dispatch

jobs:
  build-android:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - name: install Linux dependencies
        run: sudo apt-get update || true

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install npm dependencies
        run: npm install

      - name: Install java
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'zulu'

      - name: make gradlew executable
        run: chmod +x ./android/gradlew

      - name: Build android APK
        run: cd ./android && ./gradlew clean app:assembleRelease

      ## sign generated apk
      - name: Sign APK
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: test-team
          file: android/app/build/outputs/apk/release/app-release.apk
